[line :- 26] 2022-02-15 19:42:56,245 [INFO] - 
 
[line :- 26] 2022-02-15 19:42:56,245 [INFO] - ====== WebDriver manager ====== 
[line :- 26] 2022-02-15 19:42:56,984 [INFO] - Current firefox version is 96.0 
[line :- 26] 2022-02-15 19:42:56,984 [INFO] - Get LATEST geckodriver version for 96.0 firefox 
[line :- 26] 2022-02-15 19:42:58,029 [INFO] - Driver [C:\Users\Praveen.Patel\.wdm\drivers\geckodriver\win64\v0.30.0\geckodriver.exe] found in cache 
[line :- 268] 2022-02-15 19:43:06,655 [INFO] - Snowflake Connector for Python Version: 2.7.4, Python Version: 3.8.5, Platform: Windows-10-10.0.19041-SP0 
[line :- 878] 2022-02-15 19:43:06,656 [INFO] - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. 
[line :- 896] 2022-02-15 19:43:06,656 [INFO] - Setting use_openssl_only mode to False 
[line :- 704] 2022-02-15 19:43:08,880 [INFO] - query: [SELECT 1] 
[line :- 728] 2022-02-15 19:43:09,183 [INFO] - query execution done 
[line :- 704] 2022-02-15 19:43:09,184 [INFO] - query: [select * from POWERDB.PLOG.BU_CONFIG_PARAMS where PROJECT_NAME = 'CODER_BYTE_INV...] 
[line :- 728] 2022-02-15 19:43:09,684 [INFO] - query execution done 
[line :- 509] 2022-02-15 19:43:09,691 [INFO] - closed 
[line :- 512] 2022-02-15 19:43:11,663 [INFO] - No async queries seem to be running, deleting session 
[line :- 141] 2022-02-15 19:43:12,170 [INFO] - Execution Started 
[line :- 101] 2022-02-15 19:43:12,172 [INFO] - Open Coderbyte in firefox 
[line :- 103] 2022-02-15 19:43:22,200 [INFO] - pass user name 
[line :- 105] 2022-02-15 19:43:22,317 [INFO] - pass password 
[line :- 107] 2022-02-15 19:43:22,371 [INFO] - click on Login Button 
[line :- 115] 2022-02-15 19:43:30,643 [INFO] - Open plan and billing tab 
[line :- 120] 2022-02-15 19:43:43,425 [INFO] - Click on latest invoice  
[line :- 131] 2022-02-15 19:43:52,192 [INFO] - Click on download button 
[line :- 138] 2022-02-15 19:43:52,569 [ERROR] - send_mail() got an unexpected keyword argument 'Month' 
Traceback (most recent call last):
  File "c:\Users\Praveen.Patel\Desktop\python\task\main.py", line 134, in main
    bu_alerts.send_mail(receiver_email = receiver_email,mail_subject =f'JOB SUCCESS - {job_name}',mail_body = f'{job_name} completed successfully, Attached logs',attachment_location = logfile,Month =month)
TypeError: send_mail() got an unexpected keyword argument 'Month'
[line :- 145] 2022-02-15 19:44:08,334 [INFO] - File is downloaded in 6 seconds. 
[line :- 147] 2022-02-15 19:44:08,335 [INFO] - *****************Download Successfully************* 
[line :- 151] 2022-02-15 19:44:17,592 [INFO] - File is uploaded 
[line :- 152] 2022-02-15 19:44:17,592 [INFO] - It takes 56.16476321220398 seconds to run 
